### PR TITLE
Initialized html structure and incorporate the hexagonal grid

### PR DESCRIPTION
**Pull request by cesarrr93**

### CODE REVIEW

**Review by natashamullin — COMMENTED** [review]
awesome

**Review by natashamullin — COMMENTED** [review]
great

**Review by barron-a — COMMENTED** [review]
Unfortunately, it looks like this PR has a lot of conflicts with the changes Natasha and I made today while adjusting the layout.

We should probably close this without merging, but would like to make sure the team agrees. @yosuperman @natashamullin @cesarrr93  please let me know if you agree!

**Comment by cesarrr93** [comment]
Yeah we can close this I am okay with it if by the end we can add that feature I will put work into it since I been researching quite the syntax

**Pull request closed without merging**
